engines:
  pep8:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - python
  radon:
    enabled: true
    config:
      threshold: "C"
  fixme:
    enabled: true
ratings:
  paths:
    - "collectd_haproxy"
exclude_paths:
  - "tests/*"
  - "docs/*"
