language: python
python: 3.5
envs:
  - TOXENV=py27
  - TOXENV=py35
before_install:
  - pip install codeclimate-test-reporter
install: pip install tox
script: tox
after_success:
  - codeclimate-test-reporter
