language: python
python: 3.5
envs:
  - TOXENV=py27
  - TOXENV=py35
before_install:
  - pip install codeclimate-test-reporter
install: pip install tox
script: tox
after_success:
  - codeclimate-test-reporter
deploy:
  provider: pypi
  user: wglass
  password:
    secure: T+uvYexB/1O/1fEVakHIIUwu/2E1KbvYjTH6ZWPAnPHxH7u+v2xiWkOoHWwhvb+gfT/vU3PDdPVERerKpXxJr+CVkwcHA5+NEZuK7M0srPRGjTS/9YB1gnO+SBmAw7hL0IUYLDBIcCX/0sxfI1ICANSsIeh3GajL5+CCoW6yOR167VgElCt9gf5JP0EcsGcMsXbTgQGP3ePwlHaI8VuRiC6vpWUL8A6HfwbOHAPA7yGsw6gPlG7//n7bfKM0xBGZOqcEsQVyNgCHAG0y8fwxV9fh9iNcj6XnLs7qg+UwB4cj9WIRSyAd/ikniiwoNFzJ6iLeTKhrcs21KaCX2jLfYxWRqDMlayLnJ1Jlv+wNBmFjm/03jLW9pd9pXVyf5UL2iVIDGXGPfjnGcNX76bcMkBqjbZq9fPhinw07wzuXwsEPKbA+6nn1/X9Z5Zk102T3pQbBenKsEZE7F8zYNar5jQVZ3tCjTg6gLjKFYqNOQp+yWbz0YoAgsdwlrl2RGLF78arAI1eI+jABs0xlueN5DnItVl9+lvk6w4r38N4p1iaOCmG/RouPbPxZIx8IPuLHFug2RtGzscJXjXVBGdWzsxaLpw5+pVAT3sVltd/ENp2rOFEJGiVWN18NSfYebS+wkdTp/xh3VjnnJV187XegXWSyNBrsiYTxbkcmwSq76dk=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: wglass/collectd-haproxy
